### ISSUE TITLE
be able to handle a loss of client internet connection

### ISSUE THREAD

**Issue by NullVoxPopuli** [NullVoxPopuli/meshchat#18]
```
D, [2016-05-10T15:45:56.728243 #29893] DEBUG -- : SENDING on RELAY: wss://mesh-relay-in-us-1.herokuapp.com
E, [2016-05-10T15:46:16.781983 #29893] ERROR -- : unable to resolve server address: Connection timed out
E, [2016-05-10T15:46:16.782548 #29893] ERROR -- : /home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:677:in `connect_server'
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:677:in `bind_connect'
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:653:in `connect'
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/em-websocket-client-0.1.2/lib/em-websocket-client.rb:13:in `connect'
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/action_cable_client-1.3.1/lib/action_cable_client.rb:48:in `initialize'
/home/webdev/Development/meshchat/lib/meshchat/network/remote/relay.rb:28:in `new'
/home/webdev/Development/meshchat/lib/meshchat/network/remote/relay.rb:28:in `setup'
/home/webdev/Development/meshchat/lib/meshchat/network/remote/relay.rb:23:in `initialize'
/home/webdev/Development/meshchat/lib/meshchat/network/remote/relay_pool.rb:27:in `new'
/home/webdev/Development/meshchat/lib/meshchat/network/remote/relay_pool.rb:27:in `find_initial_relay'
/home/webdev/Development/meshchat/lib/meshchat/network/remote/relay_pool.rb:44:in `ensure_active_connection!'
/home/webdev/Development/meshchat/lib/meshchat/network/remote/relay_pool.rb:36:in `send_payload'
/home/webdev/Development/meshchat/lib/meshchat/network/remote/connection.rb:18:in `send_message'
/home/webdev/Development/meshchat/lib/meshchat/network/dispatcher.rb:76:in `try_dispatching_over_the_relay_first'
/home/webdev/Development/meshchat/lib/meshchat/network/dispatcher.rb:55:in `dispatch!'
/home/webdev/Development/meshchat/lib/meshchat/network/dispatcher.rb:36:in `send_message'
/home/webdev/Development/meshchat/lib/meshchat/ui/command/chat.rb:14:in `block in handle'
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/activerecord-5.0.0.rc1/lib/active_record/relation/delegation.rb:38:in `each'
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/activerecord-5.0.0.rc1/lib/active_record/relation/delegation.rb:38:in `each'
/home/webdev/Development/meshchat/lib/meshchat/ui/command/chat.rb:13:in `handle'
/home/webdev/Development/meshchat/lib/meshchat/ui/cli.rb:59:in `create_input'
/home/webdev/Development/meshchat/lib/meshchat/ui/cli/readline_input.rb:19:in `block (2 levels) in initialize'
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:977:in `block in run_deferred_callbacks'
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:974:in `times'
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:974:in `run_deferred_callbacks'
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'
/home/webdev/Development/meshchat/lib/meshchat.rb:54:in `start'
./run:12:in `<main>'
```

**Comment by NullVoxPopuli** [comment]
fixed inadvertently by the solution to #19. All messages typed without internet will be sent when internet connection is restored.
